name: Build artifacts
description: Restores build artifacts from the workflow cache.

runs:
  using: composite
  steps:
    - name: Restore build artifacts from the workflow cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        # CAUTION: The cache key originates from `.github/workflows/integrity.yml`.
        key: build:${{ hashFiles('**/*.css', '**/*.html', '**/*.ts', '**/*.tsx', '!src/**/*.fixtures.*', '!src/**/*.mocks.*', '!src/**/*.tests.*', '.env', 'mise.toml', 'pnpm-lock.yaml', 'tsconfig.json') }}
        path: dist/
        # A cache miss should never occur; the CI workflow must build the project prior to this step.
        fail-on-cache-miss: true
