/**
 * @see https://storybook.js.org/docs/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation
 * @see https://storybook.js.org/docs/essentials/toolbars-and-globals#advanced-usage
 */
export type StorybookGlobal<Value extends string> = {
	description?: string
	toolbar: {
		title?: string

		/**
		 * @see https://storybook.js.org/docs/faq#what-icons-are-available-for-my-toolbar-or-my-addon
		 */
		icon?: StorybookGlobalIconKey
		items: Array<StorybookGlobalMenuItem<Value> | Value>
		dynamicTitle?: boolean
	}
}

/**
 * @see https://storybook.js.org/docs/essentials/toolbars-and-globals#advanced-usage
 */
type StorybookGlobalMenuItem<Value> = {
	title: string
	value: Value
	right?: string

	/**
	 * @see https://storybook.js.org/docs/faq#what-icons-are-available-for-my-toolbar-or-my-addon
	 */
	icon?: StorybookGlobalIconKey
}

type StorybookGlobalIconKey =
	| "accessibility"
	| "accessibilityalt"
	| "add"
	| "admin"
	| "alert"
	| "arrowdown"
	| "arrowleft"
	| "arrowleftalt"
	| "arrowright"
	| "arrowrightalt"
	| "arrowup"
	| "azuredevops"
	| "back"
	| "basket"
	| "batchaccept"
	| "batchdeny"
	| "beaker"
	| "bell"
	| "bitbucket"
	| "book"
	| "bookmark"
	| "bookmarkhollow"
	| "bottombar"
	| "box"
	| "branch"
	| "browser"
	| "button"
	| "calendar"
	| "camera"
	| "category"
	| "certificate"
	| "check"
	| "chevrondown"
	| "chromatic"
	| "circle"
	| "circlehollow"
	| "close"
	| "closeAlt"
	| "cog"
	| "collapse"
	| "comment"
	| "commentadd"
	| "comments"
	| "commit"
	| "compass"
	| "component"
	| "contrast"
	| "copy"
	| "cpu"
	| "credit"
	| "cross"
	| "dashboard"
	| "database"
	| "delete"
	| "discord"
	| "docchart"
	| "doclist"
	| "document"
	| "download"
	| "edit"
	| "ellipsis"
	| "email"
	| "expand"
	| "expandalt"
	| "eye"
	| "eyeclose"
	| "facebook"
	| "facehappy"
	| "faceneutral"
	| "facesad"
	| "fastforward"
	| "filter"
	| "flag"
	| "folder"
	| "form"
	| "gdrive"
	| "github"
	| "gitlab"
	| "globe"
	| "google"
	| "graphbar"
	| "graphline"
	| "graphql"
	| "grid"
	| "grow"
	| "heart"
	| "hearthollow"
	| "home"
	| "hourglass"
	| "info"
	| "key"
	| "lightning"
	| "lightningoff"
	| "link"
	| "listunordered"
	| "location"
	| "lock"
	| "markup"
	| "medium"
	| "memory"
	| "menu"
	| "merge"
	| "mirror"
	| "mobile"
	| "nut"
	| "outbox"
	| "outline"
	| "paintbrush"
	| "paperclip"
	| "paragraph"
	| "phone"
	| "photo"
	| "pin"
	| "play"
	| "playback"
	| "playnext"
	| "plus"
	| "power"
	| "print"
	| "proceed"
	| "profile"
	| "pullrequest"
	| "question"
	| "redirect"
	| "redux"
	| "reply"
	| "repository"
	| "requestchange"
	| "rewind"
	| "rss"
	| "ruler"
	| "search"
	| "share"
	| "sharealt"
	| "shield"
	| "sidebar"
	| "sidebaralt"
	| "speaker"
	| "star"
	| "starhollow"
	| "stop"
	| "stopalt"
	| "structure"
	| "subtract"
	| "support"
	| "switchalt"
	| "sync"
	| "tablet"
	| "thumbsup"
	| "time"
	| "timer"
	| "transfer"
	| "trash"
	| "twitter"
	| "undo"
	| "unfold"
	| "unlock"
	| "upload"
	| "user"
	| "useradd"
	| "useralt"
	| "users"
	| "verified"
	| "video"
	| "watch"
	| "wrench"
	| "youtube"
	| "zoom"
	| "zoomout"
	| "zoomreset"
