name: Dependencies
description: Installs Node.js, pnpm, and Node.js packages.

runs:
  using: composite
  steps:
    - name: Install Node.js and pnpm with mise-en-place
      uses: jdx/mise-action@eb2f5cb41b0a8175dad2f797e3daca6fe7795a19 # v2.4.2
      #
    - name: Retrieve the path to the pnpm store
      id: pnpm-store
      # language=sh
      run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> "$GITHUB_ENV" # Use an environment variable, as step output is lost in nested composite actions: https://github.com/actions/runner/issues/2009
      shell: bash
      #
    - name: Restore the pnpm store from the workflow cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: pnpm:${{ hashFiles('mise.toml', 'pnpm-lock.yaml') }}
        path: ${{ env.PNPM_STORE_PATH }}
      #
    - name: Install Node.js packages
      # language=sh
      run: pnpm install --frozen-lockfile
      shell: bash
