# This reusable workflow verifies that the software quality meets certain standards.
# It also produces build artifacts that can be published at a later stage.
#
# It is triggered by other workflows as needed.
# It is also triggered by pushing commits to the `main` branch to prepare the workflow cache for future pull requests.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
#
# It can be triggered manually on any branch via the GitHub CLI:
#   gh workflow run integrity.yml [--ref <branch-name>]
#   gh run watch
#
# It can also be triggered manually on any branch via the GitHub web interface:
#   https://github.com/spdiswal/vitus/actions/workflows/integrity.yml

name: Integrity

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

# Cancel all previous runs of this workflow that are still in progress on the same branch.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
  # For `workflow_call` events, `github.workflow` is the caller workflow instead of this workflow.
  # The `integrity-` prefix makes GitHub Actions distinguish this job from other jobs in the caller workflow.
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  group: integrity-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      # To check out the repository.
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        #
      - name: Build the project (Vite)
        uses: ./.github/actions/task
        with:
          # CAUTION: The cache key is repeated in `.github/actions/build-artifacts/action.yml` to restore the build artifacts.
          cache-key: build:${{ hashFiles('**/*.css', '**/*.html', '**/*.ts', '**/*.tsx', '!src/**/*.fixtures.*', '!src/**/*.mocks.*', '!src/**/*.tests.*', '.env', 'mise.toml', 'pnpm-lock.yaml', 'tsconfig.json') }}
          cache-path: dist/
          task: build

  check:
    name: Clean code
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      # To check out the repository.
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        #
      - name: Verify the code style (Biome) and the type safety (TypeScript)
        uses: ./.github/actions/task
        with:
          cache-key: check:${{ hashFiles('**/*.css', '**/*.html', '**/*.json', '**/*.ts', '**/*.tsx', '.editorconfig', 'mise.toml', 'pnpm-lock.yaml') }}
          cache-path: node_modules/.cache/typescript/
          task: check

  test:
    name: Unit tests
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      # To check out the repository.
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        #
      - name: Verify the unit tests (Vitest)
        uses: ./.github/actions/task
        with:
          cache-key: test:${{ hashFiles('**/*.ts', '**/*.tsx', '.env', 'mise.toml', 'pnpm-lock.yaml', 'tsconfig.json') }}
          cache-path: node_modules/.cache/vitest/
          task: test
