# This workflow implements the first stage of the release pipeline.
# It creates a release branch and a corresponding pull request towards the `main` branch.
# Upon approving pull request, the release pipeline automatically proceeds to publish the release.
#
# It can be triggered manually on the `main` branch via the GitHub CLI:
#   gh workflow run release.yml --field version=<major.minor.patch[-prerelease][+buildinfo]>
#   gh run watch
#
# It can also be triggered manually via the GitHub web interface:
#   https://github.com/spdiswal/vitus/actions/workflows/release.yml

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The semantic version number of the new release.
        type: string
        required: true

run-name: ${{ inputs.version }}

# Cancel all previous runs of this workflow that are still in progress on the same branch.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
jobs:
  integrity:
    name: Integrity
    permissions:
      contents: read # Allow the job to call the reusable `integrity.yml` workflow.
    uses: ./.github/workflows/integrity.yml

  release-branch:
    name: Release branch
    if: github.ref_name == github.event.repository.default_branch
    needs: integrity
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions: { }
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Use a separate access token with permission to commit and push.
          token: ${{ secrets.RELEASE_AUTHOR_GH_AUTH_TOKEN }}
        #
      - name: Update release artifacts
        uses: rainstormy/updraft@23bb449c54a4e967c87a6943a1ef9a237eafdb99 # v1.2.0
        with:
          check-sequential-release: true
          files: package.json
          release-files: CHANGELOG.md
          release-version: ${{ inputs.version }}
        #
      - name: Use the release author's identity in Git
        uses: ./.github/actions/git-committer-identity
        with:
          email-address: ${{ secrets.RELEASE_AUTHOR_EMAIL_ADDRESS }}
          full-name: ${{ secrets.RELEASE_AUTHOR_FULL_NAME }}
          ssh-public-key: ${{ secrets.RELEASE_AUTHOR_SSH_PUBLIC_KEY }}
          __ssh-private-key__: ${{ secrets.RELEASE_AUTHOR_SSH___THE___PRIVATE___KEY }}
          ssh-key-fingerprints-github: ${{ secrets.SSH_KEY_FINGERPRINTS_GITHUB }}
        #
      - name: Create a release branch and a pull request
        uses: rainstormy/release/pr@eb87dc4ba5e9e89451adce4a3c62538e5ecef809 # v1.1.1
        with:
          gh-auth-token: ${{ secrets.RELEASE_AUTHOR_GH_AUTH_TOKEN }}
          version: ${{ inputs.version }}
